gyorilab/indra_db

- .gitignore
- doc/conf.py
- doc/index.rst
- doc/license.rst
- doc/modules/index.rst
- doc/modules/managers/index.rst
- doc/modules/reading/index.rst
- doc/requirements.txt
- doc/rest_api_doc/readme_link.rst
- indra_db/belief.py
- indra_db/client.py
- indra_db/managers/content_manager.py
- indra_db/reading/submit_reading_pipeline.py
- indra_db/util.py
The first pull request! (in the new repo)
This PR makes a lot of changes and improvements to the documentation.
> Documentation fixes

- indra_db/belief.py
- indra_db/client.py
- rest_api/api.py
This PR fixes:
- Logging in the rest API
- Return statements in order of the amount of evidence
- Update MockEvidence for new belief calculation requirements.
> Minor fixes

- indra_db/managers/reading_manager.py
- indra_db/reading/submit_reading_pipeline.py
Fix some minor issues in the reading pipeline resulting from the refactoring as well as some previously un-caught bugs.
> Reading fixes

- indra_db/managers/database_manager.py
- indra_db/managers/preassembly_manager.py
- indra_db/tests/test_preassembly.py
This PR makes some basic improvements to the way preassembly is run, to speed up the process and pass tests.
> Improve Preassembly

- rest_api/api.py
- rest_api/test_api.py
Add an option to set a maximum number of returned statements.
> Add max option

- indra_db/managers/database_manager.py
This PR adds the `display()` method and alters the `__str__` method of table element objects to allow a useful display of the data.
> Display results nicely.

- indra_db/client/curation.py
- indra_db/managers/database_manager.py
- indra_db/reading/read_db.py
- indra_db/tests/test_client.py
- indra_db/tests/test_preassembly.py
- indra_db/util.py
This PR implements DB support for the Evidence `source_hash` that was added in INDRA.
> Add source hash to the database.

- indra_db/util.py
Improve our method for inserting agents into the database.
> Robust agent insert

- indra_db/client/curation.py
- indra_db/client/optimized.py
- indra_db/managers/database_manager.py
- indra_db/tests/test_client.py
- rest_api/README.md
- rest_api/api.py
Refactor handling of curation to use only one table.
> Finish curation

- indra_db/client/curation.py
- indra_db/tests/test_client.py
- rest_api/api.py
Handle attempts to curate with an invalid hash gracefully at all levels.
> Handle bad hash

- indra_db/client/statements.py
This PR adds a missing import and updates an argument name in the client.
> Small fixes in client

- indra_db/util/content_scripts.py
This PR adds a new function to the content scripts that is capable of retrieving text content from the database from a text_refs dictionary.
> Add function to get text_content from text_refs

- indra_db/managers/content_manager.py
- indra_db/managers/database_manager.py
- indra_db/managers/materialized_view_manager.py
- indra_db/managers/preassembly_manager.py
- indra_db/managers/reading_manager.py
> Tidy up some minor things in the codebase.

- indra_db/reading/read_db.py
All found when running the system locally to debug issues seen on the remote system.
> Apply several fixes to the reading system

- indra_db/reading/read_db.py
- indra_db/util/distill_statements.py
- indra_db/util/insert.py
Adds TRIPS to the reader version dict, downgrade some errors/warnings, and fix a simple bug.
> Minor fixes and tweaks made when running preassembly

- indra_db/util/dump_sif.py
- rest_api/api.py
- rest_api/db_js.js
- rest_api/search_statements.html
- rest_api/secure.py
- rest_api/security_lambdas/verify_key_script.py
- rest_api/test_api.py
- rest_api/welcome.html
Implement a system for utilizing AWS Cognito to authenticate users, allowing user account specific behavior.
> Create user login features for the REST API

- indra_db/managers/database_manager.py
- indra_db/managers/materialized_view_manager.py
Implements several small fixes to the materialized view manager.
> Fix materialized views manager

- indra_db/managers/database_manager.py
- indra_db/managers/materialized_view_manager.py
Refactor materialized view management to better support PaStmtSrc.
> Refactor pa stmt src

- indra_db/managers/database_manager.py
- indra_db/managers/reading_manager.py
- indra_db/reading/submit_reading_pipeline.py
- indra_db/stats2.py
This PR primarily applies fixes to the existing structure. One key change is that the reading manager now internally iterates over each reader, rather than having the main function iterate over multiple reading managers. This PR also adds a function to get stats for the number of updates made each day.
> Take a small step towards integration of stats.

- indra_db/client/curation.py
This PR adds a function to export curated groundings from the DB as a dict that can be used in downstream applications.
> Export curated groundings

- indra_db/managers/database_manager.py
- indra_db/managers/materialized_view_manager.py
Improve logging and make task selection more uniform and robust.
> Minor fixes to materialized view creation

- indra_db/managers/preassembly_manager.py
- indra_db/tests/test_client.py
Minor changes to the preassembly code and relevant tests, made while trying to diagnose a bug in preassembly.
> Updates when running preassembly tests.

- indra_db/util/insert.py
- rest_api/test_api.py
These fixes include:
- Fixing the cleaning of agent ids (my kingdom for a colon)
- Change bad-HGNC test to be a test by NAME
- Test for pmids in the evidence for reading results.
> Make minor fixes to the REST API 

- rest_api/api.py
- rest_api/test_api.py
Fix the default namespace handling to default to searching by 'NAME'.
> Fix handling of FOS

- indra_db/managers/content_manager.py
Make a couple minor fixes/tweaks to the content manager.
> Fix content manager

- indra_db/resources/source_mapping.json
This PR moves a resource file from indra_db to indra to avoid dependency issues.
> Move source_mapping.json to indra

- indra_db/databases.py
- indra_db/managers/content_manager.py
- indra_db/managers/reading_manager.py
- indra_db/resources/build_sample_set.py
- indra_db/schemas/mixins.py
- indra_db/schemas/principal_schema.py
- indra_db/tests/test_content_manager.py
Implement the process of acquiring mesh annotations from the pubmed content as we load it.
> Get Mesh Annotations From Pubmed

- rest_api/static/curationFunctions.js
This PR resolves the expand/collapse issue for the indrabot browser results (#78)
> Move global to inline JS the INDRA HTML assembler

- indra_db/databases.py
- indra_db/reading/read_db.py
- indra_db/reading/read_db_aws.py
- indra_db/reading/report_db_aws.py
- indra_db/reading/submit_reading_pipeline.py
This PR corresponds to https://github.com/sorgerlab/indra/pull/1001 in INDRA.
This adds the ability to read content and process those from ISI.
> Add ISI Reading System

- indra_db/client/principal/curation.py
These functions are refactored from a standalone script into the client to be reusable.
> Add functions to get curator statistics

- indra_db/managers/preassembly_manager.py
- indra_db/tests/test_preassembly.py
- indra_db/util/content_scripts.py
Depends on https://github.com/sorgerlab/indra/pull/1027
> Make Adeft/Gilda usage explicit and optimize TRID-based text loading

- indra_db/managers/preassembly_manager.py
This fills a simple corner case not handled in https://github.com/indralab/indra_db/pull/86
> Skip discarded statements when continuing create.

- indra_db/managers/reading_manager.py
- indra_db/reading/read_db.py
- indra_db/reading/read_db_aws.py
- indra_db/reading/submit_reading_pipeline.py
- indra_db/tests/test_reading.py
The high-throughput reading tools have been removed from INDRA and placed into their own repo, changing many of the import paths. This PR makes the necessary updates.
> Update imports to match removal of reading tools from indra.

- indra_db/reading/submit_reading_pipeline.py
Add handling of the staggered submission feature for running large numbers of Batch jobs.
> Handle stagger

- indra_db/client/readonly/interactions.py
- rest_api/api.py
This PR removes the requirement that `limit` and `offset` be included in the request to the `relations` search endpoint.
> Fix relation search

- indra_db/util/build_corpus.py
Add a script that generates corpora of REACH content that represents all of the reach rules with as little content as possible.
> Add corpus-building script to version control.

- indra_db/managers/preassembly_manager.py
- indra_db/util/insert.py
Ensure that the hash used to compare to previous statements and the one inserted into the database are the same, and are the most recently calculated. Also fixes a bug in the naming of a column for insertion.
> Fix some bugs in preassembly.

- indra_db/managers/content_manager.py
- indra_db/schemas/principal_schema.py
This PR makes slight but significant changes to the PMC update pipeline to address issues that came to light during a recent, unprecedentedly large, dump of new fulltext content by PMC OA. In particular, new tools and a better understanding of the tools of SQLAlchemy were applied to make the update process much more efficient.
> Optimize PMC content update

- indra_db/databases.py
- indra_db/managers/content_manager.py
- indra_db/schemas/principal_schema.py
- indra_db/schemas/readonly_schema.py
- indra_db/tests/test_content_manager.py
This PR updates the mesh table so that each column is a number, not a string of a number. It also adds a uniqueness constraint based on the pmid, mesh number, and qual number trio.
This PR also adds the `pg_dump` and `pg_restore` methods to the base database API class.
> Update mesh table

- indra_db/managers/preassembly_manager.py
This PR should be merged after https://github.com/sorgerlab/indra/pull/1100 to adapt assembly to the ontology graph approach.
> Ontology graph

- README.md
- indra_db/databases.py
- indra_db/managers/reading_manager.py
- indra_db/reading/submit_reading_pipeline.py
- indra_db/schemas/readonly_schema.py
This PR builds on https://github.com/indralab/indra_reading/pull/7 to add MTI as a reader.
> Add MTI reader to DB workflow

- indra_db/schemas/principal_schema.py
A small PR to make method behavior a bit more consistent, and behaves the way the code seems to expect them to behave.
> Make pmid and pmcid handling match doi behavior.

- indra_db/managers/dump_manager.py
- indra_db/reading/read_db.py
- indra_db/reading/read_db_aws.py
- indra_db/reading/submit_reading_pipeline.py
- indra_db/schemas/principal_schema.py
This PR allows processing and storing mesh_terms parsed from MTI into the database the same way as it was working for the statements.
> Process MTI mesh_terms

- README.md
- indra_db/managers/knowledgebase_manager.py
- indra_db/schemas/principal_schema.py
This PR adds a new manager for DrugBank, and updates PathwayCommons, PhosphoSite (these two via the new pybiopax implementation of BioPAX processing) and CTD to get the latest content.
> Extend knowledge base managers

- indra_db/managers/knowledgebase_manager.py
This PR builds on changes in INDRA to integrate a new version of TAS content.
> Integrate new TAS as a knowledgebase

- indra_db/client/principal/raw_statements.py
> Fix class name

- setup.py
This is a small change to setup.py to include the files listed in MANIFEST.in, in particular the `default_db_config.ini` file which was not included before this.
> Include package data in install

- indra_db/config.py
- indra_db/databases.py
- indra_db/resources/default_db_config.ini
- indra_db/tests/test_config.py
This PR adds a class method to database objects that allows instantiating an object by instantiation a new instance on Amazon RDS. This PR also includes useful methods that output the env or config parameters that define the database instance, useful when creating a new instance.
> Codify RDS instance creation.

- indra_db/databases.py
- indra_db/managers/dump_manager.py
- indra_db/tests/test_dump_manager.py
- indra_db/util/s3_path.py
Add a function to the dump toolset that allows you to easily find the latest dump file of a given dumper. This PR also allows you to filter a list of dump "directories" by whether they are started and/or ended.
> Get the latest dump file

- indra_db/client/principal/curation.py
- indra_db/schemas/principal_schema.py
- rest_api/api.py
- rest_api/call_handlers.py
This PR also includes a small change that adds the option to input statement and evidence JSON into a curation record so that the data is not lost if/when pre-assembly is re-run.
> Convert curation API to return JSON.

- indra_db/managers/preassembly_manager.py
- indra_db/preassembly/preassemble_db.py
- setup.py
This PR includes fixes that came up when trying to resurrect the automatic preassembly pipeline.
> Fix issues with docker and preassembly

- indra_db/util/constructors.py
- rest_api/api.py
- rest_api/call_handlers.py
Apply the newly added tools from `indralab_auth` in `ui_util` added in https://github.com/indralab/ui_util/pull/12 to log usage of the db api endpoint.
> Log usage of queries/endpoints.

- indra_db/config.py
- indra_db/databases.py
- indra_db/managers/dump_manager.py
- indra_db/preassembly/preassemble_db.py
- indra_db/resources/default_db_config.ini
- indra_db/schemas/mixins.py
- indra_db/schemas/readonly_schema.py
- indra_db/tests/test_dump_manager.py
- indra_db/tests/util.py
- indra_db/util/constructors.py
- indra_db/util/insert.py
This PR also adds some fairly sophisticated testing of the dump pipeline.
> Integrate belief into the readonly database.

- indra_db/config.py
- indra_db/databases.py
- indra_db/managers/dump_manager.py
- indra_db/preassembly/preassemble_db.py
- indra_db/resources/default_db_config.ini
- indra_db/schemas/mixins.py
- indra_db/schemas/readonly_schema.py
- indra_db/tests/test_dump_manager.py
- indra_db/tests/util.py
- indra_db/util/constructors.py
- indra_db/util/insert.py
This PR also adds some fairly sophisticated testing of the dump pipeline.
> (2nd try) Integrate belief into the readonly database.

- indra_db/config.py
I added one more commit on top of @pagreene's changes to get the testing setting out correctly from the ini, I tested it with all of `testing = false`, `testing = true` and `testing = `, and it seems to work.
> Testing config fix

- indra_db/client/readonly/query.py
- indra_db/databases.py
- indra_db/managers/dump_manager.py
- indra_db/schemas/mixins.py
- indra_db/schemas/readonly_schema.py
- indra_db/tests/test_query.py
- indra_db/util/constructors.py
- rest_api/api.py
Work in the belief parameter as an option for sorting, and refactor code to allow selection of a sorting method. This PR also adds several tests of the new feature, all of which along with the old tests are passing.
> Enable sorting by belief in queries

- rest_api/call_handlers.py
Return a 401 Invalid Credentials error when a bad API key is used, instead of a lengthy internal error message.
> Return simple useful error message on auth failure.

- rest_api/api.py
- rest_api/call_handlers.py
- rest_api/test_api.py
Integrate the ability to sort by belief into the INDRA DB API. This PR also augments the rest API's documentation, and adds an explicit i-am-alive endpoint.
> Integrate Belief sorting at the REST API level.

- indra_db/databases.py
Fix the implementation of session protection so that ORM works when the database is not in protected mode.
> Re-implement session protection.

- indra_db/client/principal/__init__.py
- indra_db/client/principal/pa_statements.py
- indra_db/client/principal/raw_statements.py
- indra_db/preassembly/preassemble_db.py
- indra_db/preassembly/preassembly_submitter.py
- indra_db/tests/README.md
- indra_db/tests/db_building_util.py
- indra_db/tests/test_preassembly.py
- indra_db/tests/test_principal_client.py
This PR applies a rather minor fix to preassembly, and more importantly re-implements (resurrects) tests of preassembly. This PR also adds functionality to query raw and preassembled statements from the _principal_ database using single complex queries, and corresponding tests.
> Fix Preassembly

- README.md
- indra_db/managers/knowledgebase_manager.py
This PR adds new knowledge sources that we recently integrated with INDRA.
> Add new knowledge sources

- indra_db/cli/xdd.py
- indra_db/databases.py
This PR fixes some table-constraint-related bugs that have been causing batch jobs to fail, specifically certain reading and XDD jobs.
> Fix constraint bugs

- indra_db/databases.py
- indra_db/schemas/mixins.py
- indra_db/util/insert.py
This fixes particular bugs that cropped up when trying to run preassembly. They have been tested in-situ and fix the particular bug intended.
> Fix some bugs regarding constraints in the preassembly pipeline.

- indra_db/client/readonly/query.py
- indra_db/databases.py
- indra_db/schemas/mixins.py
- setup.py
This PR replaces a bad implementation of the paper search in which each ID was "or"ed with its neightbors with an `IN` clause, greatly improving the speed of lookup.
> Fix paper search feature

- indra_db/util/dump_sif.py
This PR addresses https://github.com/indralab/indra_db/pull/181#issuecomment-907895794 by canonicalizing IDs going into the SIF dump. Most of the work is being done by `ensure_prefix_is_needed` but some other idiosyncratic issues are also fixed (e.g., missing GO ID padding zeros, spurious EFO prefixes, etc.).
> Add function to fix IDs in SIF dump

- indra_db_service/templates/search.html
This makes it a lot nicer to look at
> Add a tiny amount of space in between count badges

- indra_db/cli/dump.py
This PR fixes a few issues in DB dump process.
> DB dump fixes

- indra_db/cli/knowledgebase.py
Integrate statements from https://github.com/sorgerlab/indra/pull/1363.
> Add manager for UbiBrowser

- indra_db/cli/content.py
This PR is a follow up to #200 and fixes an issue with uploading text refs introduced by some of the changes in the previous PR.
> Fix a problem with uploading text refs

- indra_db/cli/content.py
This PR adds methods to PmcOA class to detect publications that are available for download through FTP service but are missing from database and upload them.
> Add methods for bulk upload

- indra_db/client/principal/content.py
This PR adds one more convenience function to get text content of a given type for a list of PMIDs.
> Add another function to get text for PMIDs

- indra_db/databases.py
- setup.py
Support SQLAlchemy > 2.0 while connecting to the remote principal/readonly database
> sqlalchemy>2.0 fix

- indra_db/databases.py
- setup.py
Reserved the changes related to sqlalchemy>2.0
Need a more comprehensive scan on emmaa, ui_util, and indra_db about interacting with multiple databases.
> Reverse changes related to sqlalchemy>2.0

- setup.py
> Add PyYAML as dependency

- indra_db/readonly_dumping/export_assembly.py
- indra_db/readonly_dumping/export_assembly_refinement.py
- indra_db/readonly_dumping/rds_restore.sh
- indra_db/tests/test_readonly_pipeline.py
This PR saves the intermediate files to AWS S3 for later usage of indra cogex. See https://github.com/gyorilab/indra_cogex/pull/221.
rds_restore.sh file is added. This file makes restoring an RDS instance an automatic process. This file is unrelated to the task of syncing indra_db and CoGEx
> Save intermediate data for cogex pipeline

- indra_db/tests/test_query.py
This PR fixed the test_query.py to use the correct column name in SOURCE_GROUPS
> Make reading column to reader column

- indra_db/cli/content.py
- indra_db/cli/knowledgebase.py
- indra_db/readonly_dumping/export_assembly.py
- indra_db/readonly_dumping/export_assembly_refinement.py
- indra_db/readonly_dumping/readonly_dumping.py
- indra_db/schemas/readonly_schema.py
This PR:
- Improved find_all_pmcids_need_update() to find papers in the database missing fulltext with the scope parameter being 'fulltext'. 
- Fixed upload_text_content to modify the last_updated column 
- Fixed missing content related new statement and agent interaction with more than 2 agents.
> Knowledgebase processors and pmc_oa client fix
