gyorilab/indra_db

indra_db/client.py
indra_db/util.py

When sorting and searching for values in the database, the identical for all CHEBI ids slows look-ups significantly. This PR removes them for entry into the database.

Strip CHEBI prefix out of CHEBI ids

---

README.md
rest_api/README.md
rest_api/api.py
rest_api/test_api.py

This is essentially a complete rewrite of the documentation for the REST API, which was months out of date. This PR also:
- Allowed Statements from multiple papers to be queried in a single request (addressed a long standing issue not tracked on this repo)
- Changes the `api-key` parameter to `api_key` to match the underscore convention used by all the other parameters.
- Improves the default evidence limits to vary appropriately between endpoints.

Update the REST API documentation

---

indra_db/reading/submit_reading_pipeline.py
indra_db/tests/test_preassembly.py
indra_db/util.py

Update usage of the `get_hash` method to match INDRA.
This PR also removes the s3 file tree method from indra_db and uses the version now available in INDRA.

Update get hash

---

rest_api/README.md

Updated links to the curation manual and the `html_assembler` docs.

Link to manual

---

indra_db/client/statements.py
indra_db/tests/test_client.py

Fix a long-standing bug preventing user from getting statements directly from the database without evidence.

Fix a bug in retrieving pa statements without evidence.

---

.travis.yml
setup.py

This PR adds a simple setup.py to make the package installable as a dependency. It also simplifies .travis.yml to remove any redundant dependencies, and install all regular and test dependencies via setup.py.

Add setup and simplify Travis config

---

indra_db/util/content_scripts.py

This PR fixes the import of `dbu` broken by PR #30 on top of PR #29. It also fixes the handling of the case where there is no text_ref_id returned for a given value.

Bug fixes in getting agent text for disambiguation

---

indra_db/managers/database_manager.py
indra_db/reading/read_db.py

Make the criteria for uniqueness of statements from reading stricter, but also keep the statements that are deemed "duplicates" in a separate table. These can be examined later, and matched to "accepted" statements in the raw statements table using text hashes, matches key hashes, and the batch ids.

Improve handling of reading duplicates

---

indra_db/client/optimized.py
indra_db/tests/test_client.py

Refactor handling of multiple constraints to handle 3+ agents in a query.

Allow queries of 3+ agents

---

indra_db/managers/database_manager.py
indra_db/reading/read_db.py

Rather than ignoring readings that fail, add entries in the database with null values to mark their place. This will prevent bad content from being re-read unnecessarily. This PR also makes it so that Raw and Rejected statements are committed at the same time, to prevent inconsistent states.

Handle bad readings better

---

indra_db/managers/database_manager.py
indra_db/managers/reading_manager.py
indra_db/reading/read_db.py
indra_db/reading/submit_reading_pipeline.py
indra_db/util/insert.py

This PR also adds an agent number `ag_num` -- corresponding to the index of the agent in the deep-sorted agent list -- to the tables relating to agent metadata. This will allow the refs for a specific agent to be reconstructed just from that metadata, even if the `role` is 'OTHER'.

Fix various bugs related to reading pipeline

---

indra_db/reading/read_db.py
indra_db/reading/read_db_aws.py
indra_db/reading/report_db_aws.py
indra_db/reading/submit_reading_pipeline.py

Uses data gathered by the submitter object to plot the job submit times and run times as reported by Batch. Among other benefits, this allows some tracking of the failed jobs. This PR also standardizes datetimes to UTC.

Improve the time-logging stats.

---

indra_db/managers/database_manager.py
indra_db/managers/reading_manager.py
indra_db/reading/read_db.py
indra_db/util/distill_statements.py

Construct hashes from reading metadata rather than having ids assigned by the database. This makes ids bigints (as opposed to ints), but prevents needing to lookup the newly assigned reading ids from the database before inserting raw statements, which have a foreign key into the reading ids.
This has been tested on batch and tremendously speeds up the bulk batch reading.

Convert reading ids to be hashes

---

indra_db/managers/knowledgebase_manager.py
indra_db/tests/test_kbs.py

Add knowledge bases for PSP, Trrust, and RLIMS-P. This PR also introduces the `source` attribute of `db_info` entries, which indicates which source API corresponds to each knowledge base (e.g. biopax), as is used in belief calculations (this will allow belief to be calculated again strictly from metadata).

Add more Knowledge Bases

---

indra_db/tests/test_content_scripts.py
indra_db/util/content_scripts.py

This PR temporarily concludes work on content scripts for use in deft disambiguation. 
A new function has been added, get_stmts_with_agent_texts_in that returns dictionaries mapping agent texts to lists of containing statements. This function is similar to get_stmts_with_agent_texts_like and is useful for things such as finding all common words from a list that are being grounded by a reader.
For both get_stmts_agent_texts_in and get_stmts_with_agent_texts_like, filtering to only agent texts that have received at least one HGNC grounding in the database now works correctly. The previous implementation was not stringent enough and included agent texts that were contained in statements where at least one agent had an HGNC grounding. The new implementation checks the db_refs of the …

Content script update

---

indra_db/client/optimized.py
indra_db/managers/database_manager.py
indra_db/managers/materialized_view_manager.py

Break out separate tables for NAME and TEXT lookups, and create a separate meta table with all the other metadata. This division of labor should significantly improve lookup times. This PR also implements some basic Index support for materialized views.

Breakup lookup

---

indra_db/tests/test_sif_dumper.py
indra_db/util/dump_sif.py

This PR adds some functionality to `indra_db/util/dump_sif.py`. Particularly: argparse options as well as adding 'NAME' to the queried namespaces, allowing the final dataframe to contain the canonical name used in the database alongside the grounded ns and id for the agent.
Tests are also added.

Quick remake of sif dumper

---

indra_db/resources/source_mapping.json
indra_db/tests/test_sif_dumper.py
indra_db/util/dump_sif.py

This PR updates the sif dumper with the following:
- Add MIRBASE to NS list, and prioritize it higher than HGNC
- Rename: "hash" -> "stmt_hash" to conform with usage of IndraNet
- Use new resource file `source_mapping.json` that maps various source names in the DB to names used in the INDRA resource file `default_belief_probs.json`.

Update sif dumper

---

indra_db/client/optimized.py
indra_db/managers/database_manager.py
rest_api/api.py

This incorporates a simpler and faster method for querying statement information without needing to access the statement JSONs themselves. This PR also includes some revision of the client query itself to support different aggregation strategies.

Add endpoints for the db API using the new query methods

---

indra_db/schemas/mixins.py
indra_db/tests/test_client.py

It turns out `__table_args__` can be either tuples or dicts, so I needed to adapt the code to handle that scenario. I also added tests of the functions that were failing so such issues don't go unnoticed in future.

Fix method getting full name

---

indra_db/client/readonly/pa_statements.py
indra_db/client/tools.py
indra_db/config.py
indra_db/databases.py
indra_db/managers/readonly_manager.py
indra_db/resources/default_db_config.ini
indra_db/schemas/mixins.py
indra_db/schemas/readonly_schema.py
indra_db/util/constructors.py

Develop the code needed to seamlessly update the readonly database. The key change is that the lambda service(s) can now have the readonly database that they point to overridden via an environment variable. This allows the service to read from the principal database's copy of the readonly schema while the schema is being push to the readonly database.

Implement Readonly Updating

---

indra_db/managers/preassembly_manager.py
indra_db/schemas/principal_schema.py
indra_db/tests/util.py

Record which raw statements were skipped in a new table, discarded_statements, and skip those statements in the future to avoid re-hashing the same statements over and over again.

Skip raw statements only once

---

indra_db/client/principal/raw_statements.py
indra_db/managers/content_manager.py

This PR includes a fix to
- the `raw_statements` client, making keys into `text_refs` upper case, to overwrite any prior bad keys that were inserted by the reader.
- the content manager responsible for PMC content, making it so we actually count added content, not just added refs (again).

Apply a couple of minor Fixes

---

indra_db/databases.py
indra_db/managers/content_manager.py
indra_db/managers/reading_manager.py
indra_db/reading/read_db.py
indra_db/schemas/principal_schema.py
indra_db/upload_xdd_results.py

This PR centers around implementing a pipeline to put the results from xDD reading into the database, with empty records added for `text_content` and `reading` tables, with the DOIs used by xDD mapped to text ref IDs to maintain linking in the database.
In part to better accomplish this task, I also refactored the `text_ref` table to enable faster lookups by IDs, in particular DOIs. This also necessitated some changes to the content manager.
Changes were also made to the reading pipeline to ensure that xDD records in content and reading are ignored for the purposes of our reading.

Upload xDD content

---

README.md
indra_db/databases.py
indra_db/managers/reading_manager.py
indra_db/reading/submit_reading_pipeline.py
indra_db/schemas/readonly_schema.py

This PR builds on https://github.com/indralab/indra_reading/pull/5 to add Eidos as a reader in this repo (though I might have missed some places!). The Docker architecture is currently defined such that the image in which Eidos runs (indra_eidos_reading_docker) is built on top of indra_db_docker, therefore we'd have to merge the changes here, rebuild indra_db_docker, and then build the indra_eidos_reading_docker on top of that (if this setup is not workable, there are alternatives that we can try).

Add Eidos as a reader

---

indra_db/managers/preassembly_manager.py
indra_db/util/insert.py

Recalculate hash before all comparisons to ensure it matches insert, preventing hash conflicts on-insert. Also fixes name of column for new activity table.

Fix minor bugs in preassembly

---

indra_db/managers/content_manager.py

When trying to reconcile text refs, ensure that cleaned IDs are compared with cleaned IDs.

Ensure compare between cleaned ids in text ref merge

---

indra_db/belief.py
indra_db/managers/dump_manager.py
indra_db/schemas/readonly_schema.py
indra_db/util/dump_sif.py
indra_db/util/s3_path.py

This PR generalizes the "dump" as a class that incorporates various resources, and coordinates their generation, which is inter-related. This includes:
- the sif dump,
- the belief dump,
- the readonly database dump, and
- a dump of all pa statements as a pickle (or JSON)
The code in this branch has been tested and shown to work with only minor final modifications. It has also been improved to better allow continuation after a failed run, which was thoroughly tested. Last of all, machinery was added that ensured dumps all end up grouped together, as they should be, even when they run into a new day. These changes were integral with the changes allowing a dump to continue.

Update the Readonly Dump to include resource files.

---

indra_db/client/readonly/query.py
indra_db/client/statements.py
rest_api/api.py

This PR adds functions back in that had been removed as deprecated, with refactored interiors and deprecation warnings. Specifically, the `indra_db.client.statements` module has been added back in, in particular including the function `get_statements_by_gene_role_type`.

Add backwards-compatibility features back in

---

indra_db/databases.py
indra_db/reading/read_db.py
indra_db/util/insert.py

This PR fixes a minor issue in the dumping of statements after reading with regard to session management. Specifically, do not commit before inserting agents; this allows the entire process of inserting statements and inserting agents to occur as part of one single transaction that succeeds and fails as one, avoiding statements existing without agents and such.

Fix read db

---

indra_db/util/content_scripts.py

- Handle `title` in _get_text_content_from_trid
- Handle case where multiple contents are returned for a given text type but some of them are empty/none in _get_text_content_from_trid
- Handle existing TRID in input in _get_text_ref_id_from_text_refs

Handle some corner cases in content scripts

---

README.md
indra_db/managers/knowledgebase_manager.py

This PR adds 3 new knowledge base managers for CTD, VirHostNet and Phospho.ELM, prepared such that it can be processed in this context without complex workflows.

New knowledge bases

---

indra_db/util/s3_path.py

This PR adds the characters "." and "-" to the allowed characters in S3 bucket names. This makes the regex check compatible with all the allowed characters for bucket names (see [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules)).
I tested the regex in PyCharm.

Expand allowed characters in bucket name

---

indra_db/managers/reading_manager.py
indra_db/reading/read_db.py

Avoid content without pmids and speed up reading by constraining the content retrieved by constraining to titles and abstracts. This will also eliminate much of the content that might not have a PMID. As an added measure though, also implement graceful handling of missing PMIDs when dumping MTI results by simply skipping such records with a warning.

Avoid/handle mesh ref results without pmids.

---

indra_db/databases.py

Include the new reach version as a valid version in the `reader_versions` dictionary.

Add new reach version.

---

indra_db/managers/xdd_manager.py

It often occurs that xDD content is not given the permissions for us to read the result files for at least several hours after the file is first written. This leads to parts of each days batch of reading being skipped. Previously, a day would be marked as complete regardless of success of accessing files.
This PR makes it so that only those days for which we get _all_ of the content will be marked as done. Thus those days will be revisited in future runs until the content is finally successfully processed. Some care is taken to prevent duplicate entries in the agents table.

Tweak xDD pipeline so it revisits days we couldn't fully process

---

indra_db/managers/reading_manager.py
indra_db/reading/read_db_aws.py
indra_db/reading/submit_reading_pipeline.py

This should allow MTI to run in batches, generally reducing the likelihood of apparent hangups and job log-stall timeouts.

Add an argument for batching content reading.

---

indra_db/client/principal/raw_statements.py

Use pmid_in, pmcid_in, and doi_in to vastly speed up searches by content ID.

Make lookup of raw statements faster.

---

indra_db/client/datasets.py
indra_db/client/principal/curation.py
indra_db/client/principal/raw_statements.py
indra_db/client/statements.py
indra_db/databases.py
indra_db/managers/content_manager.py
indra_db/managers/reading_manager.py
indra_db/reading/read_db.py
indra_db/stats.py
indra_db/util/constructors.py
indra_db/util/content_scripts.py

Deprecate the `get_primary_db` function used for constructing handles to the database. Leave the function in place but with a deprecation warning, and replace all internal usages. This should solve several upstream issues with generating bad state when a session fails.

Deprecate get_primary_db

---

doc/requirements.txt
indra_db/tests/test_content_scripts.py
indra_db/util/content_scripts.py
setup.py

This PR refactors the process of getting text content from a text_refs dict. A class has been created which wraps this functionality and owns a database session that will be used for the duration of each instances life. This will be used in indra's preassembly process to allow a single database connection to be used for the gathering of text content within a preassembly run. A new dependency `cachetools` has been added. This is used in order to allow an LRUCache to be used seamlessly after chancing a cached function to a method.

Refactor text content collection

---

indra_db/managers/dump_manager.py

This PR fixes a bug were the 'fmt' attribute of the `StatementHashMeshId` dumper was misspelled.

Fix attribute misnomer

---

indra_db/managers/dump_manager.py

This PR fixes a bug where a dump of source counts from the latest DB dump were never dumped.

Add source count dumping option, run by default

---

indra_db/client/principal/content.py
indra_db/managers/knowledgebase_manager.py

This PR brings in statement validation from INDRA to block any knowledge base upload with invalid statements. It also makes a small change in reader output queries, where result can be None and has to be handled.

Add statement validation to knowledgebase manager

---

indra_db/preassembly/preassemble_db.py
indra_db/tests/test_preassembly.py

As of https://github.com/sorgerlab/indra/pull/1177, the INDRA Preassembler doesn't support multiprocessing internally. This PR removes arguments passed to the Preassembler defining the poolsize, and also surrounding code that propagates this parameter. Note that things will work fine with or without this PR (i.e., the Preassembler will not error either way).

Remove multiprocessing when calling Preassembler

---

after_zappa
rest_api/api.py
rest_api/call_handlers.py
rest_api/config.py
rest_api/static/curationFunctions.js
rest_api/templates/search.html

- Fix curation submission in old form
- Change the root lambda endpoint in `after_zappa`
- Put an end to the cut-and-paste vue testing strategy (or rather formalize it)
- Remove some logging from `url_for`.

Tidy miscellaneous odds and ends

---

setup.py

This PR adds a missing requirement to setup since it's required by downstream dependencies, see e.g., https://travis-ci.com/github/indralab/emmaa/builds/203149488.

Add termcolor to setup

---

indra_db/databases.py
indra_db/managers/dump_manager.py
indra_db/schemas/readonly_schema.py
indra_db/util/dump_sif.py

This PR makes a couple of changes and additions:
- A bug where certain statements previously were inserted into the Sif dump with mismatching name-id has been fixed
- The `Sif` dump is now created with four additional columns: `residue`, `position` (both apply to `Modification` statements only), `source_count` and `belief`. `source_count` and `belief` previously had to be added as a separate post-processing step outside the scope of the dumping process and `residue` and `position` are completely new.
- A new dumper, `ResiduePosition`, is added to grab `residue` and `position` attributes from `Modification` statements.
- The source count dumping is now done as an independent dump step and not dumped as part of making the `Sif` dump.
- The `Sif` dump now works under the assumption that the …

Sif tweaks

---

indra_db/client/principal/content.py

I tried `get_content_by_refs` to fetch some text content and ran into and issue with passing only a `trid_list` that this PR fixes. But then found that this function doesn't return for a really long time (maybe deprecated?) so as an alternative, I'm using `TextContentSessionHandler.get_text_content_from_text_refs`, which seems to work well.

Fix condition in checking for trid_list

---

indra_db/util/dump_sif.py

This PR fixes the column name in the sif dump for the source count dictionary.
The column name was previously `source_count`, but should be `source_counts` as that is what is expected in indra, see e.g. the [indranet assembler](https://github.com/sorgerlab/indra/blob/master/indra/assemblers/indranet/net.py#L117).

Fix column name in sif dump

---

indra_db/managers/content_manager.py

This is for compatibility with https://github.com/sorgerlab/indra/pull/1215 which adds support for extracting supplementary MeSH concepts from Medline XML.

Skip supplementary MeSH concepts

---

benchmarker/cli.py
benchmarker/viewer_app/benchmark.html

Update the benchmarker's interface to use Vue 3 and Bootstrap 5. This PR also fixes a pre-existing bug in the handling of new tests in a benchmark.

Update benchmarker vue

---

indra_db/cli/__init__.py
indra_db/cli/content.py
indra_db/copy.py
indra_db/databases.py
indra_db/schemas/mixins.py
indra_db/schemas/principal_schema.py
indra_db/tests/test_copy.py

This PR significantly refactors how content updates are performed, removing multiprocessing and focusing on implementing a more usable API. The PR also continues the trend of putting more database logical work into SQL that is executed on the remote server. Specifically, the process of getting the new primary key IDs from the ref table after new refs are added.
This PR also adds the `pub_year` column to text refs, and `license` column to the text content.

Refactor Content Updates

---

indra_db/cli/dump.py
indra_db/tests/test_sif_dumper.py
indra_db/util/dump_sif.py

This PR adds a check in the sif dump for entities that have the same grounding but different names. After the check, an attempt is made to normalize them using `indra.ontology.bio.BioOntology.get_name()`.

Normalize names in sif dump

---

setup.py

This line: https://github.com/indralab/indra_db/blob/master/indra_db/databases.py#L58 is not compatible with SQLAlchemy 1.4, it appears the `_extra_froms` property was removed starting with that version. This PR adds a simple limit to the setup to make sure the latest compatible version of SQLAlchemy is installed.

Limit sqlalchemy version

---

setup.py

Currently, doing a simple `import indra_db` fails if only the default dependencies are installed since both `termcolor` and `cachetools` are imported in locations that are loaded centrally in the module. So this PR makes them default dependencies to allow importing indra_db upon a basic install without extras.

Make termcolor and cachetools default dependencies

---

indra_db/preassembly/preassemble_db.py
indra_db/util/data_gatherer.py

This PR simplifies the implementation and improves some logging related to refinement finding for new statements.

Improvements for refinement finding

---

indra_db/cli/dump.py

This PR makes it possible to run `indra-db dump run all --dump-only` without having to set `INDRAROPRIMARY` as an environment variable as the readonly db is not needed when only dumping.
_NOTE: Testing the code will start a new dump run. If testing, make sure to delete the files created on S3._

Dumping updates

---

indra_db/client/readonly/query.py

This PR catches a SQLAlchemy error coming from attempting to print out queries. It simply wraps the code that errors in a try-except and ignores any attempts to print the query if it errors.
With this fix, follow-up queries that drills down to the evidence level of statements that previously gave http 500 errors now work for the client.

Catch error in debug print

---

indra_db_service/api.py
indra_db_service/templates/search.html

This PR changes the order of the statement row source badges. The dict of lists that determines the order of the badges is now set in api.py instead of in the jinja template.
Test by checking out the branch, running `indra-db-service test-service` and running a query that yields many badges and compare the ordering of the badges to the order in the source lists `db_sources` and `reader_sources` in `indra/util/statement_presentation.py`

Source badge order

---

indra_db_service/api.py
indra_db_service/config.py

This PR consists of a cherry-picked and slightly modified commit from the [ui-updates](https://github.com/pagreene/indra_db/commit/43446d8623918979fb09cc6b99ecd6cb458c7054) branch and makes it possible to run `indra-db-service test-service` from anywhere (if the command is available) by using absolute paths.

Use pathlib.Path and set absolute paths

---

indra_db_service/api.py
indra_db_service/cli/__init__.py

This PR adds the capability to test a vue-package deployment from S3 locally. When starting running `indra-db-service test-service`, add the option `--deployment <deployment name>`, where `<deployment name>` can be `latest`, `dev`, `test` etc.
This option is good as a last local test before testing the service on lambda.

Test deployed vue package files

---

indra_db_service/call_handlers.py

This PR adds a small fix that allows `expand_all` among the URL parameters for the indra_db rest API deployment.
Test by running the service locally and run a query from the "old search" and add `expand_all=true` to the set of parameters.

Fix expand_all usage

---

indra_db/cli/content.py

This PR changes the PMC manager and Manuscripts content upload process to work with changes in NIH FTP service. More specifically instead of processing a single metadata file, it processes a list of baseline and incremental files to get the PMCIDs that are missing from DB and need to be downloaded. See for the change description https://www.ncbi.nlm.nih.gov/labs/pmc/tools/ftp/#ftpupdate
P.S. It looks like we soon might need to do the same update for the PmcOA class as well since the bulk download structure is updated for both Manuscript and PMC OA. Processing the metadata files part should be almost identical. It is not a part of this PR because:
1) While the folder structure is the same for OA files and manuscripts, the structure of XMLs is different so we can't reuse the same XML …

Manuscripts content upload update

---

indra_db_service/api.py
indra_db_service/cli/__init__.py
indra_db_service/config.py

This PR makes it so that users with any credentials (an API key or account) can get all the curations, however without extra permissions the identities will be hashed and salted.
This PR adds a new config environment variable: `INDRA_DB_API_CURATOR_SALT`.
This PR also switches to using the `pathlib.Path` object for file paths.

Open up curations, with a hash

---

indra_db/cli/reading.py
indra_db/copy_utils.py

This PR updates the helper method `_get_existing` in `indra_db/copy_utils.py` to use the `_num` columns of the `text_ref` table instead of the string version of the same. This speeds up the query for the `text_ref` use case 3600-7200 times.
~_Todo before this PR is ready for review:_~
~Check that the update doesn't break the other daily update scripts (not expected).~

Use integer columns in comparison

---

indra_db_service/api.py
indra_db_service/cli/__init__.py
indra_db_service/cli/__main__.py
indra_db_service/cli/zappa_tools.py
indra_db_service/config.py

This PR along with updates in [`indra`](https://github.com/gyorilab/indra_cogex/pull/172) and [`ui_util`](https://github.com/gyorilab/ui_util/pull/20) updates the usage of flask_jwt_extended decorator to be compatible with flask_jwt_extended>3, which is a requirement for using Flask>=3.
See sorgerlab/indra#1448.

Update Flask-JWT-Extended, Flask

---

indra_db_service/templates/search_statements.html

This PR updates the form submission functionality so that JavaScript is used to get the current URL instead of what is passed from the backend in the `endpoint` parameter.

Fix form submit URL

---

docker/Dockerfile
docker/buildspec.yml
indra_db/cli/content.py
indra_db/cli/elsevier_titles.txt
indra_db/schemas/principal_schema.py
setup.py

Places where fixed applied:
**pmc_oa**
Fixed the pmc_oa processor for updating the database.
The new update() logic: Find all pmcid's that are not in the database and then get the corresponding archive set. Pass the archive set to the upload_archives(). The old update logic confused "archives" and "articles" and the update logic was wrong.
**Docker files**
Some modifications were made to make the code robust and updated.
**indra_db schema**
id in table mesh_ref_annotations: int -> bignit
**Elsevier Manager**
Add method copy_into_db()

PMC_OA, Docker and Elsevier Update

---

indra_db/cli/dump.py
indra_db/cli/reading.py
indra_db/databases.py
indra_db_service/cli/__init__.py
indra_db_service/test_api.py

_(old description from Aug 10, 2023)_
This PR adds updates associated with the latest readonly deployment and one commit that is part of the latest indra_db docker from last year.
-----
**2025 update:**
This PR is now mostly superseded by work on the new readonly pipeline. However, the changes were used in a previous dump that used the old pipeline that ran with this branch, and there are two commits that are worth keeping: one is commenting out a test that is deprecated and the other one reduces the number of IDs used per eidos reading job this.
Together this makes this PR still relevant for merging.

Readonly dumping updates

---

indra_db_service/gunicorn.conf.py

This PR adds a `gunicorn.conf.py` file with a function that is run in a separate thread to monitor the user db connection.
Depends on https://github.com/gyorilab/ui_util/pull/21.

Add gunicorn config file with `post_fork` to monitor user db connection

---

indra_db/cli/content.py
indra_db/cli/reading.py
indra_db/reading/read_db.py
indra_db/util/aws.py
indra_db/util/data_gatherer.py
indra_db/util/s3_path.py

This PR fixed some warnings or errors while we are performing the reading jobs

Reading fix

---

indra_db_service/call_handlers.py
indra_db_service/config.py
indra_db_service/gunicorn.conf.py

This PR fixes the badge link that previously had the server's localhost address instead of the db.indra.bio as base url. The fix includes creating a new `BASE_URL` environment variable, set with `INDRA_DB_API_BASE_URL`. This is then used to build the `db_rest_url` passed the to the `HtmlAssembler`.
Resolves #240.
Other changes:
- Up the user database connection check interval to 600 seconds

Fix badge url
